/* Generated by wayland-scanner 1.12.0 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *types[] = {
	&wl_surface_interface,
	NULL,
	NULL,
	&wl_surface_interface,
	&wl_surface_interface,
	&wl_surface_interface,
	&wl_surface_interface,
	NULL,
	NULL,
	&wl_surface_interface,
	&wl_surface_interface,
	NULL,
};

static const struct wl_message shell_helper_requests[] = {
	{ "move_surface", "oii", types + 0 },
	{ "add_surface_to_layer", "oo", types + 3 },
	{ "set_panel", "o", types + 5 },
	{ "slide_surface", "oii", types + 6 },
	{ "slide_surface_back", "o", types + 9 },
	{ "curtain", "oi", types + 10 },
};

WL_EXPORT const struct wl_interface shell_helper_interface = {
	"shell_helper", 1,
	6, shell_helper_requests,
	0, NULL,
};

